name: Run Python Script

on: [push]   # mỗi lần push code, GitHub sẽ tự chạy

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"   # bạn có thể đổi thành 3.12 nếu muốn

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python vth.py
